name = "ExprRules"
uuid = "e7058ba0-a568-556c-b31a-209ee9d855a8"
authors = ["Ritchie Lee <ritchie@ritchielee.net>", "Mykel Kochenderfer <mykel@stanford.edu>", "Sebastijan Dumancic <s.dumancic@tudelft.nl>"]
version = "0.5.3"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeView = "39424ebd-4cf3-5550-a685-96706a953f40"

[compat]
AbstractTrees = "0.2,0.3"
DataStructures = "0.17,0.18"
StatsBase = "0.33"
TreeView = "0.3,0.4"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
